# Generated by Django 5.2.3 on 2025-07-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='business',
            name='co_workers',
        ),
        migrations.RemoveField(
            model_name='business',
            name='method_payments',
        ),
        migrations.RemoveField(
            model_name='business',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='client',
            name='type_business',
        ),
        migrations.RemoveField(
            model_name='history',
            name='products',
        ),
        migrations.RemoveField(
            model_name='typebusiness',
            name='history',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='CatalogItem',
        ),
        migrations.DeleteModel(
            name='CoWorker',
        ),
        migrations.DeleteModel(
            name='MethodPayment',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='TypeBusiness',
        ),
    ]
