# Generated by Django 5.2.3 on 2025-07-24 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_catalog_catalogimage_catalogitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='business',
        ),
        migrations.RemoveField(
            model_name='catalogimage',
            name='catalog',
        ),
        migrations.DeleteModel(
            name='CatalogItem',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='CatalogImage',
        ),
    ]
