# Generated by Django 5.2.3 on 2025-07-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodpayment',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
