# Generated by Django 5.2.3 on 2025-08-10 06:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='business_id',
            new_name='id_business',
        ),
        migrations.AddField(
            model_name='order',
            name='id_client',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
