# Generated by Django 5.2.3 on 2025-07-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_catalog_catalogimage_catalogitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogimage',
            old_name='logo_url',
            new_name='img_url',
        ),
    ]
