# Generated by Django 5.2.3 on 2025-07-20 01:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_methodpayment_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_status', models.CharField(choices=[('new', 'Empty Cart'), ('pending', 'Pending Purchase')], default='new', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('CartPayment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_payment', to='app.cartpayment')),
            ],
        ),
        migrations.CreateModel(
            name='FollowBusiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_conversation', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('visitor', 'Visitor'), ('buyer', 'Buyer'), ('frequent_buyer', 'Frequent Buyer')], max_length=20)),
                ('clientUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='app.clientuser')),
            ],
        ),
        migrations.AddField(
            model_name='cartpayment',
            name='FollowBusiness',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_state', to='app.followbusiness'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('serv', 'Servicios'), ('prod', 'Productos')], max_length=20)),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.cart')),
            ],
        ),
    ]
