# Generated by Django 5.2.3 on 2025-08-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_business_id_order_id_business_order_id_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='carts',
        ),
    ]
