# Generated by Django 5.2.3 on 2025-07-25 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_logo_url_catalogimage_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='app.business'),
        ),
    ]
