# Generated by Django 5.2.3 on 2025-07-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cartpayment_clientuser_catalogitem_date_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='admin',
            new_name='AdminUser',
        ),
        migrations.RenameField(
            model_name='cartpayment',
            old_name='FollowBusiness',
            new_name='followBusiness',
        ),
    ]
