# Generated by Django 5.2.3 on 2025-08-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_data_order_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
