# Generated by Django 5.2.3 on 2025-07-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_admin_business_adminuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='CartPayment',
            new_name='cartPayment',
        ),
    ]
