# Generated by Django 5.2.3 on 2025-07-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_cartpayment_cart_cartpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
