# Generated by Django 5.2.3 on 2025-07-20 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_clientuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 7, 20, 1, 49, 14, 607789)),
        ),
    ]
