# Generated by Django 5.2.3 on 2025-07-20 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_clientuser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
