# Generated by Django 5.2.3 on 2025-07-21 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_adminuser_date_alter_cart_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followbusiness',
            name='clientUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_business', to='app.clientuser'),
        ),
    ]
