# Generated by Django 5.2.3 on 2025-07-21 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_followbusiness_clientuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartPayment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='app.cartpayment'),
        ),
        migrations.AlterField(
            model_name='cartpayment',
            name='followBusiness',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_payment', to='app.followbusiness'),
        ),
    ]
