# Generated by Django 5.2.3 on 2025-07-22 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_cart_cartpayment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timezone',
            old_name='business',
            new_name='timezone',
        ),
        migrations.AlterField(
            model_name='business',
            name='AdminUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='app.adminuser'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_item', to='app.business'),
        ),
    ]
