# Generated by Django 5.2.3 on 2025-07-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_timezone_timezone_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='business',
        ),
        migrations.DeleteModel(
            name='CatalogImage',
        ),
        migrations.DeleteModel(
            name='CatalogItem',
        ),
    ]
