# Generated by Django 5.2.3 on 2025-07-22 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_catalogimage_catalogitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='CatalogImage',
        ),
        migrations.DeleteModel(
            name='CatalogItem',
        ),
    ]
