# Generated by Django 5.2.3 on 2025-07-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_catalogimage_catalogitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='urlPage',
            field=models.URLField(blank=True, null=True, verbose_name='Página web'),
        ),
    ]
