# Generated by Django 5.2.3 on 2025-07-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_socialmedia_urlpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followbusiness',
            name='type',
            field=models.CharField(choices=[('payment', 'Payment'), ('visitor', 'Visitor'), ('buyer', 'Buyer'), ('frequent_buyer', 'Frequent Buyer')], default='visitor', max_length=20),
        ),
    ]
